### ISSUE TITLE
[FEAT] 이메일 인증코드 확인 API 추가

### ISSUE THREAD

**Issue by soseongha** [ajou-JSL/Backend#11]
## 🖥️ Descriptions
- 이메일 인증코드 확인 버튼을 누르면, 사용자가 입력한 이메일 인증코드 6자리를 클라이언트가 전송, 
- 이를 처리하여 올바른 코드인지 확인 후 결과를 리턴하는 API 추가 요망

## ✅ Todo
- [x] 인증코드 확인 API 추가

**Comment by 2eungwoo** [comment]
/send-mail : 기존의 이메일 발송은 그대로 유지
/verify-code : 이메일과 code를 입력하면 db랑 비교해서 검증하는 코드 추가

해당 내용대로 notion api doc 수정
