### ISSUE TITLE
[FEAT] 단체 관련 API 추가 요청

### ISSUE THREAD

**Issue by soseongha** [ajou-JSL/Backend#20]
## 🖥️ Descriptions
 - 특정 유저가 리더로 속한 단체 리스트 조회하는 API를 추가 요청드립니다. (from FRONT)
 - GET 방식
 - 유저의 memberId를 path variable로 넘김

## ✅ Todo
- [x] 특정 유저가 리더로 속한 단체 리스트 조회

## ☁️ ETC
 - 이외 내용은 'API 명세서' 문서 참고 바람

**Comment by 2eungwoo** [comment]
노션 업데이트 : API 리더의 팀 목록 조회
commit : [205fdb7](https://github.com/ajou-JSL/Backend-Multi-Module/commit/205fdb7cc365c8c69bf11e87563558989afda82e)
